title: David B. Kemp
description: The research group website of Prof. David B. Kemp (China University of Geosciences, Wuhan)
github_username: daveykemp
theme: minimal-mistakes-jekyll
logo: /images/cuglogo.png
