title: David B. Kemp's website
description: The research group website of Prof. David B. Kemp (China University of Geosciences, Wuhan)
github_username: daveykemp

theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
